### PR TITLE
 #48 Add support for relative links by prefixing them with the currently

### PR DESCRIPTION
**Pull request by nerdachse**
opened file's parent path

### CODE REVIEW

**Comment by trimental** [comment]
Thanks for this @nerdachse, I'm glad you love inlyne! The only thing I would change is the http handling, at least on macOS, paths cannot be created starting with http, which is another bug that I missed. (ie opening http://markdown.md). Perhaps a nice way to handle http would be:

```rust
let is_md = maybe_path.as_ref().map_or(false, |p| {
    p.extension().map_or(false, |ext| ext == "md")
    && !p.to_str().map_or(false, |s| s.starts_with("http"))
});
```

that way its handled before the path is created. Apart from that everything looks good and runs as expected on macOS!

**Comment by nerdachse** [comment]
@trimental thanks for that suggestion, it's way more elegant!
 
I incorporated it and took the liberty to rename `is_md` to `is_local_md`

Also note that your suggestion is NOT optional. With my code a http-link wouldn't open in the browser, but not at all. Now it works as expected!

**Comment by trimental** [comment]
Merged. Thank you for the PR ❤️w

**Comment by nerdachse** [comment]
A pleasure doing business with you, good Sir! ;)

Thanks for this awesome project!

**Pull request merged**
