### PR TITLE
chore: update taffy

### PR DESCRIPTION
**Pull request by Valentin271**
Updates taffy to the latest crates.io version.

There is no breaking change summary so I had to look in taffy's internal code to figure out which feature went were.

### CODE REVIEW

**Comment by CosmicHorrorDev** [comment]
Thanks for this! I can take a look after I get off work today

**Review by CosmicHorrorDev — APPROVED** [review]
Everything seems to be working. Thanks!

The glyphon update will likely be harder since I think there are a few other dependencies that share `wgpu` as a dependency that may have to be updated together

**Comment by Valentin271** [comment]
Took a look at it before pushing this PR (I originally wanted to update both in the same PR), it is going to be harder, there are more compiler errors right upfront. expect a PR _maybe_ next week.

**Comment by nicoburns** [comment]
Worth noting that this updates to an *older* Taffy version rather than a newer one. Which is perfectly reasonable if you want to use the released version. But that's why there's no breaking change notes: the changes haven't been released yet!

**Pull request merged**
