### PR TITLE
v0.3.2 backportapalooza

### PR DESCRIPTION
**Pull request by CosmicHorrorDev**
This bundles together all the relevant bug fixes, documentation changes, and refactors/tests that make sense for a patch release. Notably it includes all of these PRs

- #91 
- #103
- #106 
- #116 
- #109 
- #122 
- #132 
- #138 
- #147 
- #145 
- #150 
- #155 
- #154 
- #156 
- #166 
- #169 
- #171 
- #172 

~~TODO: This has that zbus issue that causes color theme detection to fail on Linux. Check to see if that's fixed when updating deps~~ Looks like the existing issue should be fixed and I'm now hitting https://bugzilla.redhat.com/show_bug.cgi?id=2239248 :upside_down_face: 

TODO: Need to follow through all the regular release steps. Bump version, update deps, draft up a more coherent description of the changes, etc.

---

- [x] Check for unused dependencies
  - `$ cargo +nightly udeps`
- [x] Update `rust-version` in `Cargo.toml`
  - `$ cargo msrv --min 1.60 -- cargo check`
- [x] Bump `version` in `Cargo.toml`
- [x] Run `cargo check` to propagate changes to `Cargo.lock`
- [x] Merge changes through a PR or directly to make sure CI passes
- [ ] Publish on crates.io
  - `$ cargo publish`
- [ ] Publish on GitHub by pushing a version tag
  - `$ git tag v{VERSION}` (make sure the branch you are on is up to date)
  - `$ git push upstream/origin v{VERSION}`
- [ ] Make a release announcement on GitHub after the release workflow finishes

### CODE REVIEW

**Comment by CosmicHorrorDev** [comment]
Whelp... this will have to be on hold until I'm no longer sick :face_with_thermometer:

**Comment by CosmicHorrorDev** [comment]
@AlphaKeks whenever you have time (no rush at all) could you check to see if this branch still fixes that panic you were experiencing that you recently fixed on `main`? I just want to make sure things are working before cutting the release

**Comment by AlphaKeks** [comment]
I can confirm that, with `nix develop nixpkgs#inlyne` followed by `cargo build` and patching the resulting binary, it does start.

What's weird is that `nix run nixpkgs#inlyne` works perfectly fine...
I can't tell why, or since when. The upstream package hasn't changed, so I assume this is something specific to my system, but I can't tell you what. It's weird because compiling inlyne manually requires this patchelf dance (and before I opened the original issue it also did with the upstream package!), but the upstream package works (now)...?

I'm honestly confused, but whatever it is, it's not inlyne's issue.

**Comment by CosmicHorrorDev** [comment]
Well happy to hear that things are working at least!

**Pull request merged**
