### PR TITLE
Have line-delta scrolling shift by 30 pixels per line

### LINKED ISSUE #3: Crashes on scroll wheel
```
thread 'main' panicked at 'not implemented', src/main.rs:172:30
```

(Linux, Wayland)

### PR DESCRIPTION
**Pull request by LovecraftianHorror**
Partially resolves #3

This could be improved by calculating a more appropriate value to scroll by line, but this change at least makes things more usable when line-delta scrolling is used

### CODE REVIEW

**Comment by trimental** [comment]
@LovecraftianHorror Considering the default text size is 16. which is scaled by `hidpi_scale` (which is around 2. on macOS) Could you test using `16. * self.renderer.hidpi_scale` for different scale factors using `inlyne --scale`.

**Comment by LovecraftianHorror** [comment]
Here's a demo when using `* 16.0 * self.renderer.hidpi_scale` on my system so you can get a better idea of how it looks. This is with `--scale 1.5` on X.org which has notoriously annoying DPI issues, so it's possible that wayland handles this better

https://user-images.githubusercontent.com/30302768/184280131-06bca6be-2664-44d4-83f9-7f55b262913d.mp4

I tried to showcase how much a "single line" is in the beginning which is why it's so jerky

**Comment by trimental** [comment]
It's hard to get a sense of how scrolling feels through a video, although it seems to scroll by about one default sized line.
Did `16.0 * self.renderer.hidpi_scale` feel good at different scales?

As long as you can move around fast enough with it, I think that approach would work better.

**Comment by LovecraftianHorror** [comment]
The scrolling feels a bit sluggish compared to other programs on my computer. The last half of the clip I sent is me scrolling pretty aggressively to give it some more context

Switching to `32.0 * self.renderer.hidpi_scale` seems to better match how much other programs on my computer scroll

**Comment by trimental** [comment]
@LovecraftianHorror Well we can always update it in the future but for now I think `32 * hidpi_scale` is a good default.

Thank you for the PR! Especially since testing on x11 is a pain on my MacBook.

**Comment by lnicola** [comment]
I think it's fine. I think wheel scroll defaults to three lines on Windows. I get about five in Firefox and 2.25 in VS Code :shrug:.

**Pull request merged**
