### PR TITLE
Fix for Wayland, Make X11 and Wayland features

### PR DESCRIPTION
**Pull request by ripe-mangos**
- Fix for #55
 - Adds `x11` and `wayland` (default) features-- so users can opt out if they so choose

### CODE REVIEW

**Comment by CosmicHorrorDev** [comment]
Thanks for the PR! Were you able to reproduce the issue in #55 to confirm that this fixes it?

**Review by CosmicHorrorDev — CHANGES_REQUESTED** [review]
Just got to take a look at the code. This is currently fixing things by removing clipboard support from all platforms which isn't desirable

`alacritty` should be a good example of how to handle this. From what I remember the event loop on wayland provides some clipboard context pointer that is used for enabling clipboard support since wayland is more fine-grained on access to these kinds of things

I've been meaning to setup a test system to reproduce the issue, so that I can verify that a fix works, but all the wayland systems I have setup have various compatibility layers setup to fix this kind of stuff. I'll work on setting up a more barebones system to reproduce tomorrow

**Comment by trimental** [comment]
@CosmicHorrorDev the actual fix for this lies in this [line](https://github.com/alacritty/alacritty/blob/32ea98deeba5f0eb6c51062cfb0fd2caa802054d/alacritty/src/clipboard.rs#L34). 

Basically clipboard events need to be driven by the Wayland event loop but because winit doesn't allow you to do this, smithay clipboard creates a new event loop to drive this in a very hacky way but you have to provide a pointer to the Wayland display.

Would have thought I would have  remembered this since I'm the one who made smithay-clipboard but 🤷.

**Comment by ripe-mangos** [comment]
@CosmicHorrorDev
 > Were you able to reproduce the issue in https://github.com/trimental/inlyne/issues/55 to confirm that this fixes it?

Yes, I'm using Hyprland 0.24.1 on Gentoo.

I don't know much about Wayland internals. This is just a quick, temporary fix until somebody that does can work on it.

[`4ed864b`](https://github.com/trimental/inlyne/pull/130/commits/4ed864b039851453637ee571f7d8f663e483b155) makes `x11` the default and `wayland` behind a feature wall.
As Wayland is still enthusiasts, I think that should be acceptable.

**Review by CosmicHorrorDev — APPROVED** [review]
This seems fine as a temporary workaround

Thanks, and congratz on your first PR here! :tada:

**Pull request merged**
