### PR TITLE
fix: filter file watcher duplicate events

### LINKED ISSUE #198: Live render partially working
# Description

Sometimes when saving a file, the live reload will not render the whole file (screen 3) or just a blank screen (screen 2).
The initial render - when starting the app - is always ok (screen 1).

Triggering the reload again will end up in one of the 3 mentioned cases.
I noticed saving with modifications will more often lead to a correct render than saving without.

It seems that the larger the file the easier it is to reproduce. While testing, I started to encounter the issue with ~250 lines, but it was very rare. 

I'd like to help more but couldn't find any log of why that happens, neither stdout/stderr or files.

From an outside point of view it seems to me like there is some non-determinism going on which causes inlyne to sort of exit early. 

# Additional details

<details><summary>Screenshots</summary>
<p>

Screen 1, working correctly on open
image

Screen 2, blank render on live reload
image

Screen 3, partially rendered after live reload (notice the size of the scrollbar compared to screen 1)
image

</p>
</details> 

I run ubuntu with i3wm and neovim v0.9.4 (if that's any relevant).

```sh
$ uname -a
Linux xubuntu 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
```sh
$ inlyne --version
inlyne 0.3.3
```
Also happens on main, 0.3.2

I mainly tested against the [ratatui breaking change file](https://github.com/ratatui-org/ratatui/blob/main/BREAKING-CHANGES.md) and the other md files in the repo.

---

Please tell me if I can be of any more help!

---

EDIT: on version 0.2.1, I don't have any blank screen, sometimes a partial render (but very rare). Hope that helps.

### PR DESCRIPTION
**Pull request by Valentin271**
This fixes #198

As discussed in the issue, I refactored the file watcher to use [notify_debouncer_full](https://docs.rs/notify-debouncer-full/latest/notify_debouncer_full/index.html).

I did so with as few modifications as possible to avoid breaking anything. The most interesting part is the `DebounceEventHandler` impl in which I basically filtered unwanted and duplicate events.
The debouncer timeout of 10ms seems good for up to 100 ~ 150Kb files on my machine.

All unit tests passed locally. I've also tested with the files I was having issues with.

I also added logs I found interesting for debugging and changed the log format to show milliseconds since the file_watcher is always faster than a second.

### CODE REVIEW

**Comment by CosmicHorrorDev** [comment]
Seems to be failing on mac, but all the file watching logic is notorious for platform specific quirks. I'll go ahead and re-run the failed jobs, but I doubt they'll pass this time (more so for my sanity). I won't be able to take too close of a look till after holidays, but I'll still be around to hit the CI button or for reviews (I also think CI should still run in your fork when you push to it for whenever I'm not around)

**Comment by Valentin271** [comment]
Alright no problem. I had a feeling it would only work on my machine, it's good you have a CI to check that. I'll fix them.

It does run on my fork after enabling it.

**Comment by CosmicHorrorDev** [comment]
Great! And do note that the watcher tests are a bit weird. They're flaky when using short delays, but longer delays suck for dev-feedback loops, so it starts with shorter delays and retries the tests a few times with increased delays on failure

Just in case the logs for the failed tests look confusing

**Comment by Valentin271** [comment]
Alright good to know, I'm currently looking at the tests and I'm suspecting the delay is too short.

**Comment by CosmicHorrorDev** [comment]
Found this issue thread. Looks like it could be relevant

https://github.com/notify-rs/notify/issues/150#issuecomment-495930414

**Comment by CosmicHorrorDev** [comment]
I just pushed a commit that should fix the `sanity` file watching tests since it looks like we were ignoring `Create` events and that was the only one getting sent

Aside: trace logs are currently getting filtered out from tests, but I'm starting to think that it'd be a good idea to retain them still

**Comment by CosmicHorrorDev** [comment]
Eh went ahead and changed that too. We really need all the info we can get when it comes to CI-driven development :upside_down_face:

**Review by CosmicHorrorDev — APPROVED** [review]
CI is green. Hope you didn't mind all the commits :partying_face: 

I'm happy to merge this as-is. Most of the issues seem to stem from MacOS sending create events instead of modify events when using the debouncer from some reason

**Comment by Valentin271** [comment]
> We really need all the info we can get when it comes to CI-driven development

Yep, I agree.

> Hope you didn't mind all the commits

No problem go ahead.

---

> Most of the issues seem to stem from MacOS sending create events instead of modify

From notify_debouncer_full docs:
> Doesn’t emit Modify events after a Create event

> I'm happy to merge this as-is

Can confirm it still works, happy to see this merged then :)

**Comment by CosmicHorrorDev** [comment]
I want to offer a huge thanks for all your help on this :)

**Comment by Valentin271** [comment]
You're welcome, I'm glad I could help. This is a great tool that I really love and want to help with and see grow (or at least not abandoned).

**Comment by CosmicHorrorDev** [comment]
There are plenty of things to work on to say the least. I can tag you in some issues that may be easier to start out with

**Comment by Valentin271** [comment]
I've seen a few already, but I wouldn't mind if you tagged the good first issues.

**Comment by CosmicHorrorDev** [comment]
Keep in mind that features don't have to be perfect to open a PR. I'm more than happy to help with draft PRs. From looking over the issues I see:

- Some keybindings stuff if you're comfortable with recursion
    - #188
- Adding history to our navigation
    - #162
    - #53
- Adding an `--edit-config` flag
    - #131
- Adding double/triple click although that may be complicated
    - #43

I picked those because they're either well tested or generally well isolated

I also have a lot of other things in an obsidian notebook, so I can start opening issues for those over the next few days. Feel free to reach out in whichever issues you want to take on so that we can talk about the general design/approach

**Comment by CosmicHorrorDev** [comment]
Opened some new issues that include a lot of potentially good starter issues along with actually labeling easy(ish) issues

https://github.com/trimental/inlyne/issues?q=is%3Aopen+is%3Aissue+label%3AE-easy

**Pull request merged**
